name: 'Deploy AWS Free Tier RDS'

#on:
  #push:
    #branches: [ master ]

env:
  AWS_REGION: 'us-east-1'
  TF_VERSION: '1.5.7'
  DB_INSTANCE_IDENTIFIER: 'free-tier-db-${{ github.run_id }}'

jobs:
  deploy-rds:
    name: 'Deploy RDS'
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ§¾ Checkout repository
        uses: actions/checkout@v4

      - name: ðŸ” Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: ðŸ› ï¸ Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: ðŸ”§ Terraform Init
        run: terraform init
        working-directory: terraform

      - name: ðŸ” Generate random DB password
        id: password
        run: |
          PASSWORD=$(openssl rand -hex 16)
          echo "DB_PASSWORD=$PASSWORD" >> $GITHUB_ENV
          echo "::add-mask::$PASSWORD"

      - name: ðŸ“‹ Terraform Plan
        run: |
          terraform plan \
            -var="aws_region=${{ env.AWS_REGION }}" \
            -var="db_instance_identifier=${{ env.DB_INSTANCE_IDENTIFIER }}" \
            -var="db_password=${{ env.DB_PASSWORD }}" \
            -var-file="rds.tfvars"
        working-directory: terraform

      - name: ðŸš€ Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="aws_region=${{ env.AWS_REGION }}" \
            -var="db_instance_identifier=${{ env.DB_INSTANCE_IDENTIFIER }}" \
            -var="db_password=${{ env.DB_PASSWORD }}" \
            -var-file="rds.tfvars"
        working-directory: terraform

      - name: ðŸ“¤ Output RDS connection details
        run: |
          echo "RDS Endpoint: $(terraform output -raw rds_endpoint)"
          echo "Username: $(terraform output -raw rds_username)"
          echo "Database Name: $(terraform output -raw rds_db_name)"
          echo "Password: **** (masked)"

  #Code:4
