apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app-1
  template:
    metadata:
      labels:
        app: flask-app-1
    spec:
      containers:
      - name: app
        image: 445567099825.dkr.ecr.us-east-1.amazonaws.com/flask-rds-app:latest
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: rds-secret