name: Build, Test & Deploy to EKS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  AWS_REGION: us-east-1                   # Update with your region
  EKS_CLUSTER_NAME: my-eks-cluster-aws-1      # Update with your cluster name
  ECR_REPOSITORY: 445567099825.dkr.ecr.us-east-1.amazonaws.com/my-flask-app
  DOCKER_IMAGE: ${{ env.ECR_REPOSITORY }}:${{ github.sha }}

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        pytest

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker image
      run: |
        docker build -t ${{ env.DOCKER_IMAGE }} .

    - name: Push Docker image
      run: |
        docker push ${{ env.DOCKER_IMAGE }}

  deploy-to-eks:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Only deploy on main branch pushes
    
    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Install kubectl
      uses: azure/setup-kubectl@v3

    - name: Configure EKS credentials
      run: |
        aws eks --region ${{ env.AWS_REGION }} update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }}

    - name: Deploy to EKS
      run: |
        # Apply Kubernetes manifests
        kubectl set image deployment/flask-app app=${{ env.DOCKER_IMAGE }} --record
        kubectl rollout status deployment/flask-app
        
        # Verify deployment
        kubectl get pods
        kubectl get svc