name: 'Deploy AWS Free Tier RDS with Terraform'

on:
  workflow_dispatch:
    inputs:
      db_password:
        description: 'Database master password'
        required: true
        type: string

env:
  AWS_REGION: 'us-east-1'
  TF_VERSION: '1.5.7'  # Terraform version
  DB_INSTANCE_IDENTIFIER: 'free-tier-db-${{ github.run_id }}'  # Unique identifier per run

jobs:
  deploy-rds:
    name: 'Deploy Free Tier RDS'
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Plan
      id: plan
      run: |
        terraform plan \
          -var="aws_region=${{ env.AWS_REGION }}" \
          -var="db_instance_identifier=${{ env.DB_INSTANCE_IDENTIFIER }}" \
          -var="db_password=${{ github.event.inputs.db_password }}" \
          -out=tfplan

    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve tfplan

    - name: Show connection details
      run: |
        echo "RDS Endpoint: ${{ steps.output.outputs.RDS_ENDPOINT }}"
        echo "Username: ${{ steps.output.outputs.RDS_USERNAME }}"
        echo "Database Name: ${{ steps.output.outputs.DB_NAME }}"
        echo "Password: [provided during workflow dispatch]"