name: Deploy RDS and Load Data

on:
  push:
    branches: [ master ]

env:
  AWS_REGION: 'us-east-1'
  TF_VERSION: '1.5.7'
  DB_INSTANCE_IDENTIFIER: 'free-tier-db-${{ github.run_id }}'

jobs:
  deploy-and-load:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Generate random DB password
        id: generate_password
        run: |
          PASSWORD=$(openssl rand -hex 16)
          echo "DB_PASSWORD=$PASSWORD" >> $GITHUB_ENV
          echo "::add-mask::$PASSWORD"

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="aws_region=${{ env.AWS_REGION }}" \
            -var="db_instance_identifier=${{ env.DB_INSTANCE_IDENTIFIER }}" \
            -var="db_password=${{ env.DB_PASSWORD }}" \
            -var-file="rds.tfvars"
        working-directory: ./terraform

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="aws_region=${{ env.AWS_REGION }}" \
            -var="db_instance_identifier=${{ env.DB_INSTANCE_IDENTIFIER }}" \
            -var="db_password=${{ env.DB_PASSWORD }}" \
            -var-file="rds.tfvars"
        working-directory: ./terraform

      - name: Write Terraform output to JSON file
        run: terraform output -json > clean_output.json
        working-directory: ./terraform

      - name: Upload Terraform outputs artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-outputs
          path: terraform/terraform-outputs.json

      - name: Parse Terraform outputs
        id: parse_outputs
        run: |
          echo "Parsing Terraform outputs..."
          DB_HOST=$(jq -r '.rds_endpoint.value' terraform/clean_output.json)
          DB_USERNAME=$(jq -r '.rds_username.value' terraform/clean_output.json)
          DB_PASSWORD=$(jq -r '.db_password.value' terraform/clean_output.json)
          DB_NAME=$(jq -r '.rds_db_name.value' terraform/clean_output.json)
          DB_PORT=$(jq -r '.rds_port.value' terraform/clean_output.json)

          echo "DB_HOST=$DB_HOST" >> $GITHUB_ENV
          echo "DB_USERNAME=$DB_USERNAME" >> $GITHUB_ENV
          echo "DB_PASSWORD=$DB_PASSWORD" >> $GITHUB_ENV
          echo "DB_NAME=$DB_NAME" >> $GITHUB_ENV
          echo "DB_PORT=$DB_PORT" >> $GITHUB_ENV

          # Mask sensitive values in logs
          echo "::add-mask::$DB_PASSWORD"
          echo "::add-mask::$DB_HOST"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Wait for RDS to be available
        run: |
          echo "Waiting for RDS endpoint to become available..."
          export PGPASSWORD=${{ env.DB_PASSWORD }}
          until pg_isready -h ${{ env.DB_HOST }} -p ${{ env.DB_PORT }} -U ${{ env.DB_USERNAME }}; do
            echo "Waiting for database connection..."
            sleep 10
          done
          echo "Database is now available!"

      - name: Load data into RDS
        env:
          DB_HOST: ${{ env.DB_HOST }}
          DB_USERNAME: ${{ env.DB_USERNAME }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}
          DB_NAME: ${{ env.DB_NAME }}
          DB_PORT: ${{ env.DB_PORT }}
        run: python scripts/load_to_rds.py


        #Code:2