name: 'Load Data to RDS via OIDC'
# on:
#   workflow_run:
#     workflows: ["Deploy AWS Free Tier RDS"]
#     types:
#       - completed

on:
  push:
    branches: [ master ]

env:
  AWS_REGION: 'us-east-1'

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  load-data:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Configure AWS via OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}
          role-session-name: github-actions-rds

      # 3. Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 4. Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      # 5. Run Python script with secrets
      - name: Load Data to RDS
        env:
          DB_HOST: ${{ secrets.RDS_HOST }}
          DB_USERNAME: ${{ secrets.RDS_USERNAME }}
          DB_PASSWORD: ${{ secrets.RDS_PASSWORD }}
          DB_NAME: ${{ secrets.RDS_DBNAME }}      # Database name
          DB_PORT: ${{ secrets.RDS_SECRET_ARN }}       # e.g., 5432 for PostgreSQL
        run: python scripts/load_to_rds.py