name: 'Load Data to RDS via OIDC'
on:
  workflow_run:
    workflows: ["Deploy AWS Free Tier RDS"]
    types:
      - completed

# on:
#   push:
#     branches: [ master ]

env:
  AWS_REGION: 'us-east-1'

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  load-data:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Configure AWS via OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}
          role-session-name: github-actions-rds

      # 3. Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 4. Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      # 5. Run Python script with secrets
      # - name: Load Data to RDS
      #   env:
      #     DB_HOST: ${{ secrets.RDS_HOST }}
      #     DB_USERNAME: ${{ secrets.RDS_USERNAME }}
      #     DB_PASSWORD: ${{ secrets.RDS_PASSWORD }}
      #     DB_NAME: ${{ secrets.RDS_DBNAME }}      # Database name
      #     DB_PORT: ${{ secrets.RDS_SECRET_ARN }}       # e.g., 5432 for PostgreSQL
      #   run: python scripts/load_to_rds.py

      - name: Download Terraform outputs artifact
        uses: actions/download-artifact@v2
        with:
          name: terraform-outputs
          path: .

      - name: Parse Terraform outputs
        id: parse_outputs
        run: |
          echo "Parsing Terraform outputs..."
          export DB_HOST=$(jq -r '.rds_endpoint.value' terraform-outputs.json)
          export DB_USERNAME=$(jq -r '.rds_username.value' terraform-outputs.json)
          export DB_PASSWORD=$(jq -r '.rds_password.value' terraform-outputs.json)
          export DB_NAME=$(jq -r '.rds_db_name.value' terraform-outputs.json)
          export DB_PORT=$(jq -r '.rds_port.value' terraform-outputs.json)

          echo "DB_HOST=$DB_HOST" >> $GITHUB_ENV
          echo "DB_USERNAME=$DB_USERNAME" >> $GITHUB_ENV
          echo "DB_PASSWORD=$DB_PASSWORD" >> $GITHUB_ENV
          echo "DB_NAME=$DB_NAME" >> $GITHUB_ENV
          echo "DB_PORT=$DB_PORT" >> $GITHUB_ENV

      - name: Load Data to RDS
        env:
          DB_HOST: ${{ env.DB_HOST }}
          DB_USERNAME: ${{ env.DB_USERNAME }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}
          DB_NAME: ${{ env.DB_NAME }}
          DB_PORT: ${{ env.DB_PORT }}
        run: python scripts/load_to_rds.py
