name: 'Load Data to RDS via OIDC'
# on:
#   workflow_run:
#     workflows: ["Deploy AWS Free Tier RDS"]
#     types:
#       - completed
on:
  push:
    branches: [ master ]

env:
  AWS_REGION: 'us-east-1'

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  load-data:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Configure AWS via OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}
          role-session-name: github-actions-rds

      # 3. Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform-version: "1.5.7"

      # 4. Get Terraform outputs as JSON
      - name: Fetch Terraform Outputs
        id: tf-outputs
        run: |
          cd terraform
          terraform output -json > outputs.json
          {
            echo "TF_OUTPUTS<<EOF"
            cat outputs.json
            echo "EOF"
          } >> $GITHUB_OUTPUT
        working-directory: ./terraform


      # 5. Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Install dependencies
        run: pip install -r scripts/requirements.txt


      # 6. Run Python script
      - name: Load Data to RDS
        env:
          TF_OUTPUTS: ${{ steps.tf-outputs.outputs.TF_OUTPUTS }}
        run: python scripts/load_to_rds.py