name: Update Existing EC2 Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

env:
  AWS_REGION: 'us-east-1'  # Change to your region
  EC2_INSTANCE_ID: 'i-0e5aed48bf4deef4f'  # Replace with your EC2 instance ID
  DEPLOYMENT_DIR: '/home/ec2-user/customer-app/customer-app'  # Replace with your deployment directory
  EC2_HOST: '44.204.161.247'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY_EC2 }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ env.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Copy app files to EC2
        run: |
          scp -r ./customer-app/* ec2-user@${{ env.EC2_HOST }}:${{ env.DEPLOYMENT_DIR }}

      - name: Restart FastAPI service
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@${{ env.EC2_HOST }} "sudo systemctl restart fastapi-app.service"
