name: Update Existing EC2 Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

env:
  AWS_REGION: 'us-east-1'  # Change to your region
  EC2_INSTANCE_ID: 'i-1234567890abcdef0'  # Replace with your EC2 instance ID
  DEPLOYMENT_DIR: '/home/ec2-user/customer-app/customer-app'  # Replace with your deployment directory
  SSH_KEY_SECRET: 'SSH_KEY_EC2'  # Name of your GitHub secret containing SSH private key

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.$SSH_KEY_SECRET }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Copy files to EC2
        run: |
          scp -r ./frontend/dist/* ec2-user@${{ secrets.EC2_HOST }}:$DEPLOYMENT_DIR

      - name: Restart application (if needed)
        run: |
          ssh ec2-user@${{ secrets.EC2_HOST }} "sudo systemctl restart fastapi-app.service"  # Adjust service name